version: '3'

services:
  ##
  # NOTICE:
  # env BOX_IP is defined only for kdev services
  # This is the ip address of the VM which runs docker containers
  ##

  dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - ${BOX_IP}:53:53/tcp
      - ${BOX_IP}:53:53/udp
    cap_add:
      - NET_ADMIN
    command: "--address=/test/${BOX_IP}"
    restart: always
    network_mode: "bridge"
  mail:
    image: mailhog/mailhog
    environment:
      # Use easier domain name for mailhog
      VIRTUAL_HOST: mail.test
      VIRTUAL_PORT: 8025
    ports:
      # Map mailhog into host machine port
      # This port is used in production too
      - 25:1025
    restart: always
    network_mode: "bridge"
  signaler:
    image: onnimonni/signaler
    environment:
      GENERATOR: "self-signed"
    volumes:
      # Mount .kdev folders to store certificates in
      - ${HOME}/.kdev/certs:/data/certs
      - ${HOME}/.kdev/ca:/data/ca

      # Mount docker socket so that signaler can auto create certificates
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    network_mode: "bridge"
