version: '3'

services:
  ##
  # NOTICE:
  # env BOX_IP is defined only for kdev services
  # This is the ip address of the VM which runs docker containers
  ##

  dnsmasq:
    image: andyshinn/dnsmasq
    ports:
      - ${BOX_IP}:53:53/tcp
      - ${BOX_IP}:53:53/udp
    cap_add:
      - NET_ADMIN
    command: "--address=/test/${BOX_IP}"
    restart: always
    network_mode: "bridge"
  mail:
    image: mailhog/mailhog
    environment:
      # Use easier domain name for mailhog
      VIRTUAL_HOST: mail.test
      VIRTUAL_PORT: 8025
    ports:
      # Map mailhog into host machine port
      # This port is used in production too
      - 25:1025
      - 8025:8025
    restart: always
    network_mode: "bridge"
  signaler:
    image: onnimonni/signaler
    environment:
      GENERATOR: "self-signed"
    volumes:
      # Mount .kdev folders to store certificates in
      - ${HOME}/.kdev/certs:/data/certs
      - ${HOME}/.kdev/ca:/data/ca

      # Mount docker socket so that signaler can auto create certificates
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    network_mode: "bridge"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    volumes:
      # Make elasticsearch persistent
      - /usr/share/elasticsearch/data
      - ${HOME}/.kdev/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    network_mode: "bridge"
    container_name: elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.3.2
    volumes:
      - ${HOME}/.kdev/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ${HOME}/.kdev/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    network_mode: "bridge"
    container_name: logstash
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    volumes:
      - ${HOME}/.kdev/kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    network_mode: "bridge"
    container_name: kibana
    depends_on:
      - elasticsearch
